### ISSUE TITLE
Gmp has empty interface. Packaging bug?

### ISSUE THREAD

**Issue by Kakadu** [mirage/ocaml-gmp#10]
```
➜  ~ echo '#use "topfind";;\n#require "gmp";;\n#show Gmp;;' | ocaml -noinit
        OCaml version 4.10.1

# - : unit = ()
Findlib has been successfully loaded. Additional directives:
  #require "package";;      to load a package
  #list;;                   to list the available packages
  #camlp4o;;                to load camlp4 (standard syntax)
  #camlp4r;;                to load camlp4 (revised syntax)
  #predicates "p,q,...";;   to set these predicates
  Topfind.reset();;         to force that packages will be reloaded
  #thread;;                 to enable threads

- : unit = ()
# /home/kakadu/.opam/4.10.1+flambda/lib/gmp: added to search path
/home/kakadu/.opam/4.10.1+flambda/lib/gmp/gmp.cma: loaded
# module Gmp : sig end
# 
➜  ~ opam install gmp                                                      
[NOTE] Package gmp is already installed (current version is 6.2.1).
```
CC @thelortex

**Comment by dinosaure** [comment]
The goal of this package is to allow us to cross-compile `libgmp.a` for MirageOS. Then, we use `zarith` as the library which exposes what you want 👍 - note that we use a specific version of `zarith` available here: https://github.com/TheLortex/Zarith

**Comment by Kakadu** [comment]
So, it looks like that library is not intended to be used by itself without cross-compilation. Could you add that to README?

**Comment by dinosaure** [comment]
> So, it looks like that library is not intended to be used by itself without cross-compilation. Could you add that to README?

It can be used without cross-compilation. This package lets us to _vendor_ `libgmp.a` (via `opam monorepo`) instead of to use `conf-gmp` (which is compiled for the host system). Then, you can use `ocaml-gmp` + `Zarith` for your program (as you use `conf-gmp` + `Zarith`), the _plus_ is about `dune` and its compilation context.

With `ocaml-gmp` and `opam monorepo`, you can decide a certain compilation context _via_ `dune` (such as some C flags) and apply them transparently when you want to compile `libgmp.a`. But I agree with you that we should improve the `README.md`.
